---
- name: Install required packages
  apt:
    name: "{{item}}"
    state: installed
  with_items:
      - unzip
  when: ansible_os_family == 'Debian'

- name: Install required packages
  yum:
    name: "{{item}}"
    state: installed
  with_items:
    - unzip
  when: ansible_os_family == 'RedHat'



- name: Create wildfly user
  user:
    name: "{{wildfly_user}}"
    createhome: no
    shell: /bin/bash

- name: copy tar file to source
  copy:
    src: /opt/jboss/wildfly-10.0.0.Final.tar.gz
    dest: /opt
    owner: "{{wildfly_user}}"
    group: "{{wildfly_user}}"
    mode: 0777

- name: Download and extract tarball
  unarchive:
 #   src: "http://download.jboss.org/wildfly/10.0.0.Final/wildfly-10.0.0.Final.tar.gz"
    src: /opt/jboss/wildfly-10.0.0.Final.tar.gz
    dest: "{{wildfly_basedir}}"
    creates: "{{wildfly_basedir}}/wildfly-{{wildfly_version}}"
    remote_src: yes
    owner: "{{wildfly_user}}"
    group: "{{wildfly_user}}"
    mode: 0777

- name: Make symbolic link to wildfly home
  file:
    src: "{{wildfly_basedir}}/wildfly-{{wildfly_version}}"
    dest: "{{wildfly_home}}"
    state: link
    owner: "{{wildfly_user}}"
    group: "{{wildfly_user}}"
    mode: 0777

- name: Make sure config dir exists
  file:
    path: /etc/wildfly
    state: directory
    owner: "{{wildfly_user}}"
    group: "{{wildfly_user}}"

- name: Copy config file
  copy:
    src: wildfly.conf
    dest: /etc/wildfly/wildfly.conf
    mode: 0644

- name: Copy service script
  template:
    src: wildfly.service
    dest: /lib/systemd/system
    mode: 0644

- name: Link to systemd service
  file:
    src: /lib/systemd/system/wildfly.service
    dest: /etc/systemd/system/multi-user.target.wants/wildfly.service
    state: link
    mode: 0777

- name: Copy management console user configuration
  template:
    src: "{{item}}"
    dest: "{{wildfly_home}}/domain/configuration"
    owner: "{{wildfly_user}}"
    group: "{{wildfly_user}}"
    mode: 0777
  with_items:
    - mgmt-users.properties
    - mgmt-groups.properties

- name: Change auth dir permissios to allow CLI deployments
  file:
    path: "{{wildfly_home}}/domain/tmp/auth"
    mode: 0744
    state: directory

- name: Copying host.xml configuration file
  template: src=host.xml dest={{wildfly_home}}/domain/configuration/

#- name: replacing name as slave
#  replace:
#    dest: /opt/wildfly/domain/configuration/host.xml
#    regexp: 'name="master"'
#   replace: 'name="slave"'

#- name: Added server identities  in the file
#  blockinfile:
#    dest: /opt/wildfly/domain/configuration/host.xml
#    insertafter: <security-realm name="ManagementRealm">
#    block: |
#          <server-identities>
#           <secret value="bWF0aWxkYUBqYm9zcw=="/>
#          </server-identities>
#- name: uncomment 
#  replace:  
#    dest: /opt/wildfly/domain/configuration/host.xml
#    regexp: '# BEGIN ANSIBLE MANAGED BLOCK'
#    replace: ''

#- name: uncomment
#  replace: 
#    dest : /opt/wildfly/domain/configuration/host.xml
#    regexp: '# END ANSIBLE MANAGED BLOCK' 
#   replace: ''

#- name: replacing local
#  replace:
#    dest: /opt/wildfly/domain/configuration/host.xml
#    regexp: '<local/>'
#    replace: <!-- <local/> -->

#- name: Insert a line at the end of a file.
#  lineinfile:
#    dest: /opt/wildfly/domain/configuration/host.xml
#    line:  <remote protocol="remote" host="192.168.10.14" port="9999" username="matilda" security-realm="ManagementRealm"/>
#    insertbefore: </domain-controller>

#- name: updating address
#  replace:
#    dest: /opt/wildfly/domain/configuration/host.xml
#    regexp: '{jboss.bind.address.management:127.0.0.1}'
#    replace: '{jboss.bind.address.management:0.0.0.0}'

#- name: adding updating address
#  replace:
#    dest: /opt/wildfly/domain/configuration/host.xml
#    regexp: '{jboss.bind.address:127.0.0.1}'
#    replace: '{jboss.bind.address:0.0.0.0}'


- name: copy control script
  template:
    src: launch.sh
    dest: /opt
    owner: "{{wildfly_user}}"
    group: "{{wildfly_user}}"
    mode: 0777

- name: Copy execute script
  template:
    src: run.sh
    dest: /opt
    owner: "{{wildfly_user}}"
    group: "{{wildfly_user}}"
    mode: 0777


- name: execute the script
  command: sh /opt/run.sh

#-name: execute the script
#  command: sh "{{wildfly_home}}"/bin/run.sh

#- name: adding user
  #shell: sh /opt/wildfly/bin/add-user.sh  test1  test1
#  raw: "export JAVA_HOME=/opt/jdk1.8.0_161 && sh /opt/wildfly/bin/add-user.sh {{user_name}} {{password}}"
